format="$directory$git_branch$git_status$fill$sudo$fill$cmd_duration$fill$memory_usage$localip$line_break$character"

[fill]
symbol = " "
style = ""

[directory]
format = "(#403d52 bold)[î—¿ $path](#e0def4 bold)"

[status]
symbol = "ğŸ”´"
format = "[$symbol $common_meaning$signal_name$maybe_int](bold red bold) "
map_symbol = true
disabled = false

[git_branch]
format = "[ | ](#403d52 bold)[îœ‚ $branch](#f6c177 bold)"

[git_status]
format = "( [\\[$all_status$ahead_behind\\]](#eb6f92 bold))"

[sudo]
disabled = false
allow_windows = true
symbol = "î¼"
format = "[$symbol](#6e6a86 bold)"

[cmd_duration]
format = "[ó°€  $duration](#6e6a86 bold)"

[memory_usage]
disabled = false
threshold = -1
format = "[î¿… $ram](#f6c177 bold)"

[localip]
format = "[ | ](#403d52 bold)[î¼‰ $localipv4](#f6c177 bold)"
ssh_only = false
disabled = false

[character]
success_symbol = "[âœ](#e0def4 bold)"
error_symbol = "[âœ—](#eb6f92 bold)"
