format="$hostname$directory$git_branch$git_status$golang$python$nodejs$terraform$cmd_duration$fill$sudo$memory_usage$time$line_break$character"

[fill]
symbol = " "
style = ""

[hostname]
ssh_only = false
format =  "[ $hostname ](bg:#dbff00 black bold)"
disabled = false

[directory]
format = "[ ğŸ“ $path ](bg:white black bold)"

[memory_usage]
disabled = false
threshold = -1
symbol = " "
format = "[ $ram ](bg:#ff69b4 black bold)"

[status]
symbol = "ğŸ”´"
format = "[$symbol $common_meaning$signal_name$maybe_int](bold red bold) "
map_symbol = true
disabled = false

[git_branch]
symbol = "ğŸŒ± "
format = "[ $symbol$branch ](bg:#dbff00 black bold)"

[git_status]
format = "([\\[$all_status$ahead_behind\\] ](bg:#dbff00 red bold))"

[golang]
format = "[ $symbol$version ](bg:white black bold)"

[python]
format = "[ $symbol$version( $virtualenv) ](bg:white black bold)"

[nodejs]
format = "[ $symbol$version ](bg:white black bold)"

[terraform]
format = "[ $symbol$workspace ](bg:white black bold)"

[sudo]
disabled = false
allow_windows = true
format = "[ $symbol](bg:white black bold)"

[cmd_duration]
format = "[ â° $duration ](bg:blue white bold)"

[time]
disabled = false
format = "$fill[ ğŸ•“ $time ](bg:white black bold)"
